exercises/chapter 18/pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas."""
from django.urls import path
from . import views
app_name = 'pizzas'

urlpatterns = [
# Home page
path('', views.index, name='index'),

# Page that shows all available pizzas.
path('pizzas', views.pizzas, name='pizzas'),

# Detail page for a single pizza.
path('pizzas/<int:pizza_id>/', views.pizza, name='pizza')
]

exercises/chapter 18/pizzeria/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls'))
]

exercises/chapter 18/pizzeria/pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """Represent a pizza that can be ordered from the pizzeria."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name
    
class Toppings(models.Model):
    """A topping that can be added to a pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

exercises/chapter 18/pizzeria/pizzas/views.py
from django.shortcuts import render
from .models import Pizza

def index(request):
    """The home page for pizzas."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all orders."""
    pizzas = Pizza.objects.order_by('date_added')
    content = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', content)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.all()
    content = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', content)

exercises/chapter 18/pizzeria/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> - 
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}
{% endblock content %}

exercises/chapter 18/pizzeria/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>Welcome to the Pizzeria! We hope you'll find a pizza that you like. :)</p>
{% endblock content %}

exercises/chapter 18/pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>{{pizza}}</p>
  <ul>
    {% for topping in toppings %}
      <li>
        <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
        <p>{{topping}}</p>
      </li>
    {% empty %}
      <li>There are no toppings for this pizza yet.</li>
    {% endfor %}
  </ul>
{%endblock content %}

exercises/chapter 18/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>Pizzas</p>
  <ul>
    {% for pizza in pizzas %}
      <li><a href="{% url 'pizzas:pizza' pizza.id %}">{{pizza.name}}</a></li>
    {% empty %}
      <li>No order has been made yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}